const router = require('express').Router();
const c = require('./users.controller');
const { authenticateToken } = require('../../middleware/authenticate');
const { requirePermission, requireCurrentUser } = require('../../middleware/authorize');
router.use(require('./users.diagnostics').requestDiagnostics);
router.use(authenticateToken);
router.get('/profile/me', requireCurrentUser, c.profile);
router.get('/', requirePermission('users.read'), c.list);
router.get('/:id', requirePermission('users.read'), c.detail);
router.post('/', requirePermission('users.create'), c.create);
router.patch('/:id', requirePermission('users.update'), c.mutate('update'));
router.patch('/:id/status', requirePermission('users.status'), c.mutate('status'));
router.patch('/:id/role', requirePermission('users.assignRole'), c.mutate('assignRole'));
router.delete('/:id', requirePermission('users.status'), c.mutate('status'));
router.use(require('../auth/security-errors'));
module.exports = router;
